# Generated by Django 3.1.2 on 2021-02-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Project_Name')),
                ('start_date', models.DateField(verbose_name='Start_Date')),
                ('end_date', models.DateField(verbose_name='End_date')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='FullName')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee')),
            ],
        ),
    ]
