# Generated by Django 3.1.2 on 2021-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210204_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('ProjectManager', 'ProjectManager'), ('BackendDeveloper', 'BackendDeveloper'), ('FrontendDeveloper', 'FrontendDeveloper'), ('Designer', 'Designer')], db_index=True, default='BackendDeveloper', max_length=30, null=True, verbose_name='Designation'),
        ),
    ]
