# Generated by Django 3.1.2 on 2021-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210207_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_project', to='employee.Project'),
        ),
    ]
